version: 2
jobs:

  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      # - run:
      #     name: Package Python Lambda Zip
      #     command: |
      #       mkdir deps && touch deps/__init__.py
      #       pip install requests -t deps
      # zip -r output/bundle.zip lambda_function.py deps/*
      - run:
          name: Test
          command: |
            python lambda_function.py
      - run:
          name: Bundle
          command: |
            mkdir output
            zip -r output/bundle.zip lambda_function.py
      - persist_to_workspace:
          root: output
          paths:
            - bundle.zip

  deploy:
    docker:
      - image: circleci/python:3.8
    steps: 
      - attach_workspace:
          at: output
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Publish Lambda
          command: |
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            export AWS_DEFAULT_REGION=${AWS_REGION}
            export FUNCTION_NAME=hello_world
            aws lambda update-function-code --function-name ${FUNCTION_NAME} --zip-file fileb://output/bundle.zip
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master